### ISSUE TITLE
Rename Zip.ls function

### ISSUE THREAD

**Issue by MartinSStewart** [agu-z/elm-zip#1]
I wanted to get all the entries from a zip file I had parsed. I looked for `entries`, `toEntries`, etc but couldn't find anything. It was only after I looked at the type signature of every function that I found `ls` (and shortly thereafter realize it referred to the terminal command). 

I think it would be more discoverable if it was renamed to `entries` or `toEntries`, especially since there's already a function called `fromEntries`. `ls` is especially unclear if you're accustomed to working in Windows where it would be called `dir` instead.

**Comment by agu-z** [comment]
@MartinSStewart I'm glad you brought this up! I agree that people are not necessarily familiar with the `ls` command from UNIX or expecting to find a reference to it in this library. I figured it wouldn't be a problem since I mentioned it early in the docs, but I get that a more intuitive name is just nicer.

`Zip.toEntries` gives me the feeling that there's some transformation going on, and while you could abstractly say that this is what all pure functions do, this feels more like accessing content. So I like your `Zip.entries` suggestion, which follows a typical naming pattern in core libraries.  (e.g. `Dict.keys`)

Since I'd be introducing a breaking change, I would also like to revise `Zip.byPath`. Do you think it's a good name? Maybe it should be renamed to `getEntry`.

Thank you!

**Comment by MartinSStewart** [comment]
> I figured it wouldn't be a problem since I mentioned it early in the docs, but I get that a more intuitive name is just nicer.

I think a common use case is to find a package, skim the readme, and then install it and view the function documentation in one's IDE. So having documentation at the top of the module isn't a fool proof way to make sure it gets noticed since the user might be seeing the module like this:
![image](https://user-images.githubusercontent.com/5068391/111216807-27f79f80-85d5-11eb-9450-fa9150355e58.png)


`getEntry` might make more sense if you go with the `Dict` idea. I don't think `byPath` is too bad though so either way is fine by me.

**Comment by agu-z** [comment]
> think a common use case is to find a package, skim the readme, and then install it and view the function documentation in one's IDE. 

Yeah, I do this too. Good point. I'll think more about the documentation-less experience of my APIs from now on :) 

Thank you again for the feedback! I'll push a new version this week.

**Comment by agu-z** [comment]
[3.0.0](https://package.elm-lang.org/packages/agu-z/elm-zip/3.0.0/Zip) is out with this change. Thanks again for the suggestion!
