### ISSUE TITLE
Update deps to work with latest justinmimbs/date

### ISSUE THREAD

**Issue by simonh1000** [agu-z/elm-zip#2]
latest is 4.0.1 and had all sort of challenges in using your library alongside other packages that were hoping for the latest version of justinmimbs/date

**Comment by agu-z** [comment]
Fixed in `3.0.1`.

It looks like I was only using two very straightforward functions from `justinmimbs/date`, so I decided to drop the direct dependency altogether.
Note I still depend on it indirectly through `justinmimbs/time-extra` but that package is compatible with the latest `Date`, and expect the author to keep them that way.
